### ISSUE TITLE
Extending Documentation of minirocket multivariate

### ISSUE THREAD

**Issue by bdudzik** [angus924/minirocket#10]
Hello, 

The implementations for minirocket multivariate (both here and on sktime) mention that it is a naive extension of the univatiate version, but do not give any clearer explanation of what is actually happening under the hood. Looking directly at the source code for this version does not help that much either, as it is fairly hard to read. 

Could you extend the documentation on the repository with a (coarse) description of how the algorithm was extended to handle multivariate data and/or add some comments to the source code in that regard?

Thanks!

**Comment by angus924** [comment]
Hi @bdudzik, good point, I'll add a note explaining the extension to multivariate.

In the meantime, in summary, the multivariate version works by assigning a random subset of channels (up to a maximum of 9 channels) to each kernel/dilation combination.  Each kernel/dilation then operates on this subset of channels (using the same kernel/dilation per channel), rather than just a single channel.

Thanks for the suggestion.
