### ISSUE TITLE
Minimum length time series

### ISSUE THREAD

**Issue by TommasoBendinelli** [angus924/minirocket#11]
Hi, What is the minimum length of a time series for Minirocket? I have tried with time series of length 4 but It throws me an error

**Comment by angus924** [comment]
Hi Tommaso,

The minimum length is 9, but you can get around this in a couple of ways, e.g., padding the time series to a length of at least 9, or making a small edit to the code so that padding is always "on" (rather than alternating between padding/not padding).

Does this help?

Thanks very much.

Best,

Angus
