### ISSUE TITLE
Are minirocket.py and minirocket_dv.py the implementation for the same Mini-Rocket algorithm?

### ISSUE THREAD

**Issue by dbq233** [angus924/minirocket#15]

**Comment by angus924** [comment]
Hi @dbq233, they are very similar.  Both do essentially the same thing.  The key difference is that the main MiniRocket implementation (`minirocket.py`) samples bias values from randomly-selected training examples, whereas the deterministic variant (`minirocket_dv.py`) samples bias values using the entire training set.  So there is some randomness in the default implementation (`minirocket.py`), but the deterministic variant (`minirocket_dv.py`) will always produce the same result.  Overall, the accuracy of both approaches is almost exactly the same.  The deterministic variant is slower, because it has to do a lot more work to extract the bias values.
